name: Run Testsigma tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Process script to run test
        run: |
          bash ${GITHUB_WORKSPACE}/process_tests.sh
          ls -l
          echo "Successfully sent testing process to Testsigma!"

