name: Run Testsigma tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Process script to run test
        run: |
          chmod +x ./process_tests.sh
          bash ./process_tests.sh
          echo "Successfully sent testing process to Testsigma!"
        shell: bash

