name: Run Testsigma tests

on:
  push:
    paths:
      - "testsigma/**"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Process script to run test
        run: |
          bash ./testsigma/process_tests.sh
          echo "Successfully sent testing process to Testsigma!"

