name: Run Testsigma tests

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Process script to run test
        run: |
          bash process_tests.sh
          echo "Successfully sent testing process to Testsigma!"

